const winden = [];

winden.push({ name: 'Mikkel', salary: 700 });
winden.push({ name: 'Jonas', salary: 200 });
winden.push({ name: 'Martha', salary: 300 });
winden.push({ name: 'Ulrich', salary: 600 });
winden.push({ name: 'Katarina', salary: 700 });
winden.push({ name: 'Noa', salary: 200 });
winden.push({ name: 'Hannah', salary: 300 });
winden.push({ name: 'Claudia', salary: 400 });
winden.push({ name: 'Magnus', salary: 500 });
winden.push({ name: 'Charlotte', salary: 600 });
winden.push({ name: 'Regina', salary: 800 });
winden.push({ name: 'Bartoz', salary: 900 });
winden.push({ name: 'Adan', salary: 500 });
winden.push({ name: 'Eva', salary: 400 });
winden.push({ name: 'Peter', salary: 500 });
winden.push({ name: 'Helge', salary: 300 });
winden.push({ name: 'Tronte', salary: 300 });
winden.push({ name: 'franzisca', salary: 400 });
winden.push({ name: 'Alexander', salary: 600 });
winden.push({ name: 'Erick', salary: 800 });
